### ISSUE TITLE
DMA Bus error

### ISSUE THREAD

**Issue by Snicks321** [JaCzekanski/Avocado#19]
* Build: 03/07/2018. Commit (e5a52a9)
* OS: Windows 10 64-Bits
* Bios: SCPH1001
* Hardware: CPU: I3 7100, GPU: NVidia 1050, RAM: 8GB.
* Game: Tomb Raider Chronicles (SLUS-01311)
* Behavior: The game is playable, just need to press Enter (Start) to fastboot, because it gave me errors until I press start to fastboot, error below. But everytime a blackscreen appears, I have to press Start to fastbooting, or will be on that blackscreen forever
* Screenshots/Videos: Nothing to screen, only the error
* Log: [log.txt](https://github.com/JaCzekanski/Avocado/files/2161155/log.txt)

And another thing, can't press more than 2 bottons, if I press BUTTON_UP and BUTTON_LEFT, and then  press BUTTON_SQUARE it will not work, but if I stop pressing BUTTON_LEFT, I will start working again.

----------------------------------------------------------------------------------------------------------
Also, same build and everything else

* Game: Digimon Rumble Arena (SLUS-01404)
* Behavior: The game start, look for Memory Card, everything work, I said no, and then black screen, and on the console it said 
[log (SLUS-01404).txt](https://github.com/JaCzekanski/Avocado/files/2161261/log.SLUS-01404.txt)
then if I press Enter (Start) to fastboot, the console stop showing those errors, and the game works on intro screen, showing DEMO Mode, and press Start to continue.

If I press Start, the game enter on main screen, the emulator crash, I don't have it on Visual Studio to debug, but this is the screen 
![error digimon rumble arena](https://user-images.githubusercontent.com/12128168/42247626-005fd276-7ef8-11e8-9f19-50c529ceda9b.png)

**Comment by JaCzekanski** [comment]
Thanks for you report.
I'd be nice if you update [Compability page](https://github.com/JaCzekanski/Avocado/wiki/Compability) on wiki. (link to this issue in games you mentioned)

> But everytime a blackscreen appears, I have to press Start to fastbooting, or will be on that blackscreen forever

Right now Avocado does not support MDEC which is Movie Decoder unit. You'll see black screen instead of movie. As you have noticed - most of these can be skipped with Start button.
Will be done in #20 

> And another thing, can't press more than 2 bottons, if I press BUTTON_UP and BUTTON_LEFT

You were using keyboard? It looks like your keyboard have limitation which prevents this key combination - https://en.wikipedia.org/wiki/Rollover_(key)
Remapping controls to different scheme should help this.
It's working fine on my laptop.



As for second game:
> If I press Start, the game enter on main screen, the emulator crash, I don't have it on Visual Studio to debug, but this is the screen

I was able to recreate crash myself. 
It's happening when rendering triangles - tex4bit function accesses VRAM outside of bounds. Clipping and masking of VRAM positions should be done in "triangle" method.
This shouldn't happen in the first place - I'll take a closer look at this issue soon.

**Comment by JaCzekanski** [comment]
Fixed in 14d7977.

**Comment by Snicks321** [comment]
Thanks for the repply, I will follow your project, Idk how to add the Tomb Raider to the Game Compability list, new on github.

Btw, u block me on twitter :'(

**Comment by Snicks321** [comment]
About the keyboard, is a gamming one, and I also use it with the ePSXe and works fine.

**Comment by JaCzekanski** [comment]
@Snicks321 Whoops, sorry about Twitter, shouldn't be blocked now. My bad.

https://github.com/JaCzekanski/Avocado/wiki/Compability
There is an "Edit" button on the top-right side of the page.

Add new entry to document (copy another one and edit accordingly). 

I'll investigate this issue with keyboard later.

**Comment by Snicks321** [comment]
@JaCzekanski Okay, thanks, I will add Tomb Raider, and change the Digimon Rumble Arena, is now playable

**Comment by Snicks321** [comment]
@JaCzekanski Done, edited the Compability, added Tomb Raider, and changed Digimon Rumble Arena

EDIT: My bad about keyboard, it was Rollover from keypad and the up-down buttons, I change square, cross, circle and triangle to WASD and works just fine.
