### ISSUE TITLE
CHD & PBP Support

### ISSUE THREAD

**Issue by RinMaru** [JaCzekanski/Avocado#28]
Will this emu support those at some point?

**Comment by JaCzekanski** [comment]
For this moment Avocado supports only uncompressed CD images (.img, .bin). Any other format such as .ecm or .pbp has to be uncompressed/converted to raw binary.

I'm planning to add support for more file formats - for starters I'll be improving handling of dumps with multiple tracks (.cue with multiple .bin).
Later I would like to add .sub file support (required for games that has anti-piracy mechanisms).

I don't know what is the most popular way to store disc images - I know that .pbp was used with PS1 games dumped PSP, I'm guessing there are people using that format.
As for .chd - I haven't heard about it and I never found dumps using it. From what I found it is used in MAME project - @RinMaru could you give little more info about where it is used?

**Comment by RinMaru** [comment]
PBP is probably more or less used more often since it can store multidisc games into a single file but nothing supports it outside PCSX R and ePSXe. CHD for PS1 is used by Libretro only currently but it has higher compression ratio then PBP but doesn't support packing multidisc games into a single file.

**Comment by JaCzekanski** [comment]
I would love to support every file format that exists to make Avocado as user friendly as possible, but also I don't want to waste my time on implementing features that will be rarely used.

I'm leaving this issue opened - if there is more interest in foreign file format support then please leave comment in this discussion.

**Comment by Aerocatia** [comment]
CHD is currently supported by MAME and Beetle PSX in RetroArch. Disc images can be compressed to it from BIN/CUE using a small tool that comes with MAME.

It's not the most popular format due to the Beetle support not being that old and MAME not being that great for playstation emulation, however it's a good choice going forward as it has the best compression ratio and keeps everything nicely in one file.

As for for PBP, really there are two formats. You have the encrypted Sony PBP that is only supported by Beetle PSX outside the PSP/PS3, and the unofficial unencrypted custom PBP with different compression. The latter being used by PSP custom firmware and some more emulators like ePSXe PCSXR and also Beetle.

As for what compression formats should be added, I'd say CHD and Sony PBP would be good choices, with CHD being the most important and Sony PBP being a nice extra so people could run 100% official dumps. The unofficial PBP format is not really very good for use outside the PSP, and is mostly used because it was all there was at the time.

**Comment by JaCzekanski** [comment]
@Vaporeon Thanks for your feedback.
I didn't know that .pbp were indeed two separate formats - that's very useful information.

I'll focus on .chd support for now.

**Comment by JaCzekanski** [comment]
> Added .chd support

I only tested it on 3 discs:
- THPS2 - Data (Mode2)
- Moto Racer - Data (Mode2) + Red Book Audio
- Witcher 2 OST - Red book audio only CD

Works ok.

Files were compressed using chdman 0.199

**Comment by JaCzekanski** [comment]
Continued discussion in #41.
