### ISSUE TITLE
Cant run on more than 6fps

### ISSUE THREAD

**Issue by rickomax** [JaCzekanski/Avocado#69]
Built the emulator for Windows 64 and can't exceed 6fps on debug mode, what should be wrong?

**Comment by JaCzekanski** [comment]
Debug mode is very slow in Visual studio due to the usage of STL containers which are completely unoptimized and have multiple boundary checks which are absent in Release builds.
You should be able to speed it up a little by disabling [iterator debugging](https://docs.microsoft.com/en-us/cpp/standard-library/iterator-debug-level?view=vs-2019) (define `_ITERATOR_DEBUG_LEVEL=0` for the whole project) and/or disable buffer security checks.

Building the emulator in Release mode will take care of all of those issues.
