### ISSUE TITLE
Wiki Compatibility List

### ISSUE THREAD

**Issue by literalmente-game** [JaCzekanski/Avocado#8]
I've been following the progress for some time now and I think it's a good idea to create a simple compatibility list (using an wiki page in this repo) to keep track of the compatibility/progression/regressions.

Could follow the same structure from here https://github.com/inolen/redream/wiki/Compatibility or something similar. If you agree I can start adding my test results and open issues to link to the list (as a quick way for users to know what was already tested and what games have the same issues)

**Comment by JaCzekanski** [comment]
Hello @literalmente-game,
Thanks for your input, I'm surprised that someone is following my progress.

Avocado is still my pet project which I'm developing in my spare time and I didn't think that somebody would consider using it to play games.
I don't focus on making specific games playable, rather hacking some part of emulator allowing to boot game (like I did with Crash Bandicoot 1) and continue with the development of different parts (eg. 3d renderer).
But starting a wiki is a good way to show that project is moving forward.

I'm ok with copying structure from Redream - I will create a wiki and put games that I use to test new versions. I should also create better Readme file.

Right now every commit triggers Windows build on AppVeyor so testing new versions shouldn't be a problem.
If you would like me to implement some features - feel free to create an issue on Github.

**Comment by JaCzekanski** [comment]
Wiki page is ready: https://github.com/JaCzekanski/Avocado/wiki/Compability

Because my emulator does not implement fast booting (you have to see whole BIOS intro everytime) I recommend using [UniROM](http://www.psxdev.net/forum/viewtopic.php?t=722). Just copy any of .rom files (I use unirom_caetlaNTSC_plugin.rom from V6) to data/bios directory and edit "extension" field in config.json:
`"extension": "data/bios/unirom_caetlaNTSC_plugin.rom"`

From now on you can fastboot using Start button (Enter by default) or slowboot using R2 button (keypad * by default).
You can even open **Caetla** with Select button (Right shift) and run .exe from disc directly. Helpful if game has multiple executables or when testing games from Demo discs.

TAB key will disable framelimiting allowing game to run faster.

Games can be loaded using "iso" field in config.json or by using Drag and drop when running emulator. Cue files should be used, but emulator should load .bin or .img files as well (but without Red Book audio).

I'm using NTSC bioses (SCPH-101, SCPH-7001, SCPH-1001). PAL will load, but resolutions and timings are still NTSC.

**Comment by literalmente-game** [comment]
I'm happy to see you've already made the wiki list and agreed with my idea. I'll add new entries as I test other titles, closing this issue as the list was already created.
