### ISSUE TITLE
RELEASE for rickomax's version?

### ISSUE THREAD

**Issue by R7CrazyCanucks** [JaCzekanski/Avocado#85]
Hi i wanted to know when will there be a release for rickomax's version of Avocado that has Free Camera Tool & OBJ exporting?

**Comment by JaCzekanski** [comment]
Hello @R7CrazyCanucks
I completely forgot about that fork, but I promised Rickomax to port it over the latest Avocado version and will try to do it this week.

Sadly, due to the amount of modification in that fork, I won't be able to merge changes into main codebase so it'll be available as a separate version for download.

**Comment by JaCzekanski** [comment]
Build should be available there: [https://avocado-builds.czekanski.info/?branch=feature/3d-screenshot](https://avocado-builds.czekanski.info/?branch=feature/3d-screenshot) (when it builds)

**Comment by rickomax** [comment]
Hey @JaCzekanski thanks a lot for merging!
I could not merge it yet as the many changes that Avocado had during the development.
